modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="advancerepair"
version="1.0"
displayName="Advance Repair"
description='''
Repair system with custom materials and XP scaling.
'''