modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="advancerepair"
version="1.0"
displayName="Advance Repair"
logoFile="advancerepair.png"
description='''
Repair system with in-game materials and XP scaling.
'''
